# Generated by Django 4.0.3 on 2022-04-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_comment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorizing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='user')),
                ('surname', models.CharField(max_length=200, verbose_name='surname')),
                ('education', models.CharField(max_length=300, verbose_name='education')),
                ('birth_date', models.DateField(verbose_name='birthday date')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('phone', models.CharField(max_length=400, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'Қолданушы',
                'verbose_name_plural': 'Қолданушылыр',
            },
        ),
    ]
